### ISSUE TITLE
Black Screen on play a video in full-screen mode

### ISSUE THREAD

**Issue by Ox9n** [teamairship/react-native-android-fullscreen-webview-video#2]
When I try to play video in full-screen mode in webView
a black screen showing and make the app stop working 
I need a help to fix this problem 

**Fixed** 

After I start looking to files I found the issue in the file VideoWebChromeClient.java 
You just need to remove this line from the file 
`    ((View) mWebView.getRootView()).setVisibility(View.GONE);
`

**Comment by amhinson** [comment]
I’ve only been able to get it working on an actual device. The emulator did the same thing for me. Can you try that?

**Comment by Ox9n** [comment]
@amhinson I try it on galaxy s8+ (with android oreo ) and the same problem 😢

**Comment by honestxll** [comment]
same issue,and it was broken when I press the back button😭

**Comment by amhinson** [comment]
Just merged in a potential change. Can anyone check against master if it works?

**Comment by denny64** [comment]
@amhinson - Latest commit works well, thanks! FYI - when doing yarn install react-native-android-fullscreen-webview-video it installs the original version. Prob need to update the package version

**Comment by amhinson** [comment]
Ok excellent. I didn't have any time to test it out, so I just wanted to make sure it worked well before making a new version. Should be live on npm now!
